// 這是題目庫檔案 
module.exports = [
    { normal: "新年", undercover: "跨年" },
    { normal: "牛奶", undercover: "豆漿" },
    { normal: "烤肉", undercover: "涮涮鍋" },
    { normal: "壁紙", undercover: "壁貼" },
    { normal: "男友", undercover: "前男友" },
    { normal: "情人節", undercover: "光棍節" },
    { normal: "沐浴乳", undercover: "肥皂" },
    { normal: "勇往直前", undercover: "全力以赴" },
    { normal: "語無倫次", undercover: "詞不達意" },
    { normal: "公車", undercover: "捷運" },
    { normal: "同學", undercover: "同桌" },
    { normal: "冠軍", undercover: "第一名" },
    { normal: "圖書館", undercover: "書店" },
    { normal: "羅密歐與茱麗葉", undercover: "梁山伯與祝英台" },
    { normal: "紅燒牛肉麵", undercover: "清燉牛肉麵" },
    { normal: "高麗菜", undercover: "大白菜" },
    { normal: "牛肉乾", undercover: "豬肉乾" },
    { normal: "口香糖", undercover: "棒棒糖" },
    { normal: "薰衣草", undercover: "滿天星" },
    { normal: "生活費", undercover: "零用錢" },
    { normal: "班導師", undercover: "教官" },
    { normal: "氣泡水", undercover: "汽水" },
    { normal: "筆電", undercover: "平板" },
    { normal: "流星花園", undercover: "繼承者們" },
    { normal: "蜘蛛人", undercover: "蝙蝠俠" },
    { normal: "富二代", undercover: "高富帥" },
    { normal: "警察", undercover: "保全" },
    { normal: "神鵰俠侶", undercover: "天龍八部" },
    { normal: "雲霄飛車", undercover: "海盜船" },
    { normal: "鴨舌帽", undercover: "漁夫帽" },
    { normal: "雙胞胎", undercover: "龍鳳胎" },
    { normal: "腳踏車", undercover: "機車" },
    { normal: "橘子", undercover: "柳丁" },
    { normal: "首爾", undercover: "東京" },
    { normal: "護唇膏", undercover: "口紅" },
    { normal: "結婚", undercover: "訂婚" },
    { normal: "眼鏡", undercover: "隱形眼鏡" },
    { normal: "衛生紙", undercover: "濕紙巾" },
    { normal: "海豚", undercover: "海獅" },
    { normal: "印表機", undercover: "影印機" },
    { normal: "滷肉飯", undercover: "雞肉飯" }, // 替換魚香肉絲
    { normal: "UNIQLO", undercover: "NET" }, // 替換森馬
    { normal: "台南", undercover: "高雄" }, // 替換杭州
    { normal: "蝴蝶", undercover: "蜜蜂" },
    { normal: "魔術師", undercover: "魔法師" },
    { normal: "枕頭", undercover: "抱枕" },
    { normal: "降龍十八掌", undercover: "如來神掌" },
    { normal: "作家", undercover: "編劇" },
    { normal: "醜小鴨", undercover: "灰姑娘" },
    { normal: "端午節", undercover: "中秋節" },
    { normal: "高跟鞋", undercover: "厚底鞋" },
    { normal: "金莎", undercover: "大波露" }, // 替換金絲猴
    { normal: "洗髮精", undercover: "潤髮乳" },
    { normal: "葡萄", undercover: "藍莓" },
    { normal: "小籠包", undercover: "水煎包" },
    { normal: "蔡依林", undercover: "張惠妹" }, // 替換張韶涵
    { normal: "烏龍茶", undercover: "綠茶" }, // 替換鐵觀音
    { normal: "電風扇", undercover: "冷氣" },
    { normal: "玫瑰", undercover: "康乃馨" },
    { normal: "油條", undercover: "雙胞胎" }, // 油條配雙胞胎比較合理
    { normal: "玻璃", undercover: "鏡子" },
    { normal: "十面埋伏", undercover: "四面楚歌" },
    { normal: "臉盆", undercover: "水桶" },
    { normal: "作文", undercover: "日記" },
    { normal: "麵包", undercover: "蛋糕" },
    { normal: "婚紗", undercover: "禮服" },
    { normal: "麥克風", undercover: "大聲公" },
    { normal: "白雪公主", undercover: "灰姑娘" },
    { normal: "手機", undercover: "市話" },
    { normal: "狀元", undercover: "榜首" },
    { normal: "辣椒", undercover: "芥末" },
    { normal: "棉被", undercover: "床單" },
    { normal: "獎牌", undercover: "獎盃" },
    { normal: "鬍子", undercover: "眉毛" },
    { normal: "井底之蛙", undercover: "鼠目寸光" },
    { normal: "餅乾", undercover: "洋芋片" },
    { normal: "電影", undercover: "電視劇" }, // 替換小品
    { normal: "盒子", undercover: "箱子" },
    { normal: "吉他", undercover: "烏克麗麗" },
    { normal: "胖子", undercover: "壯漢" },
    { normal: "媽媽", undercover: "婆婆" },
    { normal: "哈密瓜", undercover: "西瓜" },
    { normal: "青梅竹馬", undercover: "兩小無猜" },
    { normal: "臭豆腐", undercover: "皮蛋豆腐" }, // 替換麻婆豆腐
    { normal: "動物", undercover: "植物" },
    { normal: "水餃", undercover: "鍋貼" },
    { normal: "洗衣粉", undercover: "洗衣精" },
    { normal: "手帕", undercover: "毛巾" },
    { normal: "牛郎", undercover: "織女" }, // 替換董永
    { normal: "童話", undercover: "神話" },
    { normal: "暗戀", undercover: "單戀" },
    { normal: "太監", undercover: "娘娘腔" },
    { normal: "漢堡", undercover: "三明治" }, // 替換肉夾饃
    { normal: "積木", undercover: "樂高" },
    { normal: "冬粉", undercover: "米粉" }, // 替換馬鈴薯粉
    { normal: "原子筆", undercover: "鋼筆" }, // 替換晨光
    { normal: "洗衣機", undercover: "烘衣機" }, // 替換乾洗機
    { normal: "直髮", undercover: "捲髮" },
    { normal: "絲襪", undercover: "內搭褲" }, // 替換秋褲
    { normal: "榴槤", undercover: "波羅蜜" },
    { normal: "羽絨衣", undercover: "棉襖" }, // 替換鵝毛
    { normal: "雨傘", undercover: "陽傘" },
    { normal: "蝴蝶", undercover: "飛蛾" },
    { normal: "大便", undercover: "咖哩" }, // 經典題目
    { normal: "麥當勞", undercover: "肯德基" },
    { normal: "Facebook", undercover: "Instagram" },
    { normal: "LINE", undercover: "Messenger" },
    { normal: "Google", undercover: "Yahoo" },
    { normal: "YouTube", undercover: "Netflix" },
    { normal: "可樂", undercover: "雪碧" },
    { normal: "珍珠奶茶", undercover: "波霸奶茶" },
    { normal: "鹹酥雞", undercover: "雞排" },
    { normal: "火鍋", undercover: "壽喜燒" },
    { normal: "颱風", undercover: "龍捲風" },
    { normal: "地震", undercover: "海嘯" },
    { normal: "感冒", undercover: "過敏" },
    { normal: "牙刷", undercover: "牙膏" },
    { normal: "安全帽", undercover: "鋼盔" },
    { normal: "口罩", undercover: "面具" },
    { normal: "耳機", undercover: "喇叭" },
    { normal: "滑鼠", undercover: "觸控板" },
    { normal: "鍵盤", undercover: "鋼琴" },
    { normal: "太陽", undercover: "月亮" },
    { normal: "星星", undercover: "路燈" },
    { normal: "醫生", undercover: "護士" },
    { normal: "老師", undercover: "教授" },
    { normal: "老闆", undercover: "主管" },
    { normal: "小狗", undercover: "小貓" },
    { normal: "獅子", undercover: "老虎" },
    { normal: "大象", undercover: "犀牛" },
    { normal: "企鵝", undercover: "北極熊" }, // 經典地理題
    { normal: "蘋果", undercover: "梨子" },
    { normal: "香蕉", undercover: "芭蕉" },
    { normal: "鳳梨", undercover: "釋迦" }, // 形狀有點像
    { normal: "番茄", undercover: "柿子" },
    { normal: "玉米", undercover: "筍子" }
];